function [lb_u, ub_u, lb_d, ub_d] = bounds_sensitivity_exact_subsystems_AOCS()


% AOCS
% * x: Design parameters
%       * x(1) = pointing accuracy, deg
%       * x(2) = offset between centre of gravity and centre of pressure, m
%       * x(3) = area normal to velocity vector, m^2
%       * x(4) = area normal to sun line, m^2
%       * x(5) = reflectance factor
%       * x(6) = spacecraft residual dipole, A*m^2
%       * x(7) = drag coefficient
%       * x(8) = actuator type: [0 0.5) = magtorq, [0.5 1] = thruster
%       * x(9) = specific impulse, s
%       * x(10) = burn time for momentum dumping, s
%       * x(11) = slew angle, deg
%       * x(12) = time for slew maneuvre, s
%       * x(13) = initial tumbling rate, rad/s
%       * x(14) = spin angle, deg    
%
% * ep: Environmental parameters
%       * ep(1) = orbit period, s
%       * ep(2) = mean planet's magnetic field stregth, T
%       * ep(3) = mean incident solar radiation, W/m^2
%       * ep(4) = mean dynamic pressure, Pa
%       * ep(5) = mean gravitational field strength, deg
%       * ep(6) = angle between spacecraft z axis and nadir vector, deg
%       * ep(7) = spacecraft moment of inertia about x axis, kg*m^2
%       * ep(8) = spacecraft moment of inertia about y axis, kg*m^2
%       * ep(9) = spacecraft moment of inertia about z axis, kg*m^2
%       * ep(10) = thruster moment arm, m
%       * ep(11) = number of thrusters
%       * ep(12) = number of dumping maneuvres during S/C lifetime
%       * ep(13) = number of slew maneuvres during S/C lifetime


lb_d = [5 ...
       0.005 ...
       0.034 ...
       0.034 ...
       0.5 ...
       0.5/1000 ...
       2 ...
       0 ...
       0.1 ...
       0.1 ...      
       10 ...
       30 ...       
       0.1 ...
       0.1 ...
       ];     

ub_d = [10 ...
       0.02 ...
       0.15 ...
       0.15 ...
       0.7 ...
       1.5/1000 ...
       2.5 ...
       0.4 ...
       1 ...
       1 ...       
       60 ...
       90 ...       
       0.2 ...
       5 ...
       ];

   
   
lb_u = [4000 ...
       1e-5 ...
       1000 ...
       1e-8 ...
       1e-8 ...
       5 ...
       0.0417*0.9 ...
       0.1083*0.9 ...
       0.1417*0.9 ...       
       0.1 ...
       0.1 ...
       0.1 ...
       0 ...
       ];    

ub_u = [8000 ...
       1e-3 ...
       5000 ...
       1e-5 ...
       1e-5 ...
       10 ...
       0.0417*1.1 ...
       0.1083*1.1 ...
       0.1417*1.1 ...  
       5 ...
       5 ...
       5 ...
       1 ...
       ];

   

   
   
return